spring:
  application:
    name: MyApplication

  profiles:
    default: "docker"

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
